---

- name: Derive individual secrets from base secret
  set_fact:
    "{{ item }}": "{{ (item + jitsi_meet_base_secret | string) | hash('sha1') }}"
  loop:
    - jitsi_meet_videobridge_secret
    - jitsi_meet_videobridge_password
    - jitsi_meet_jicofo_password
    - jitsi_meet_turn_secret
  when: jitsi_meet_base_secret is defined

- name: Derive videobridge nickname
  set_fact:
    jitsi_meet_videobridge_muc_nickname: "{{ (jitsi_meet_base_secret | string + 'jvb_muc_nick') | to_uuid }}"
  when: jitsi_meet_base_secret is defined

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'