---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu2004-jitsi-meet
    box: generic/ubuntu2004
    interfaces:
      - network_name: private_network
        ip: 192.168.247.80
provisioner:
  name: ansible
  become: True
lint: |
  set -e
  yamllint .
  ansible-lint
